path = "/home/ManishDeb/crm-soap/"

local java = loadLanguage("java")
Helpers.Table.print(java.getNodeTypes())
-- print("staticCastHandling")
-- -- Logger.level = 2
-- 
-- local findNativeQuery = [[
--   (method_invocation (identifier) @method_name (#eq? @method_name "createNativeQuery")
--     arguments: (argument_list [(string_literal) (binary_expression)] @first_arg (class_literal) @second_arg (#eq? @second_arg "Object[].class")))
-- ]]
-- 
-- local findCasts = [[
--   (cast_expression type: (type_identifier) @cast_type value: (array_access) @cast_value) @cast
-- ]]
-- 
-- local wrappers = {
--   Character = "StringUtilities.valueOf(",
--   String = "StringUtilities.valueOf(",
--   Long = "NumberUtilities.toLong(",
--   Integer = "NumberUtilities.toInteger(",
-- }
-- -- path = io.read()
-- 
-- local Git = gitOpen(path)
-- Git:resetHead()
-- local branch = "test-b-1"
-- if not Git:branchExists(branch) then Git:branchCreate(branch) end
-- Git:checkout(branch)
-- 
-- walk(path,
--     { ext = {".java"}, ignore = { "**/hibernate/**", "**/datatypes/**", "**/api/**"},
--       recursive = true, filesOnly = true },
--   function(file, git)
--     local r = read(file.path);
--     if(file.path == "") then return end
--     local tree = java:parse(file.path, true)
--     local w = write(file.path)
--     local edt = Editor()
-- 
--     tree:query(findNativeQuery,
--       function(c)
--         if c.second_arg.text ~= "Object[].class" then return end
--         tree:query(findCasts,
--         function(match)
--           if match.cast.row <= c.second_arg.row then return end
--           if match.cast.row > c.second_arg.row + 200 then return end
--           local wrapper = wrappers[match.cast_type.text]
--           if not wrapper then return end
--           local repl = wrapper .. match.cast_value.text .. ")"
--           edt:write(match.cast, repl);
--         end)
--       end)
-- 
--     edt:applyAndSaveValidOnly(tree, w)
--     git:add(file.path)
-- end)

-- print("find createQuery instances")
-- 
-- gitOpenOrInit(path)
-- 
-- local hits = findInFiles(path, [[createQuery\(\s*.*,\s*Object\[\]\.class\s*\)]], { ext = { ".java" } })
--   
-- local i = 1;
-- for _, h in ipairs(hits) do
--   for _, m in ipairs(h) do
--     local pos = m
--     print(pos.path .. ":" .. pos.row .. ":" .. pos.col)
--     print(pos.text)
--     print(i);
--     i = i+1;
--   end
-- end
-- 
